[package]
name = "amethyst-imgui"
version = "0.3.0"
description = "imgui library for amethyst"
license = "CC0-1.0"
authors = ["Awpteamoose <cargo@awpteamoose.my.to>", "Walter Pearce <jaynus@gmail.com>"]
repository = "https://github.com/jaynus/amethyst-imgui"
readme = "README.md"
edition = "2018"

[dependencies]
#amethyst = { version = "0.11", features = ["vulkan", "shader-compiler"] }
amethyst = { path = "../amethyst", features = ["nightly", "saveload", "vulkan", "gltf", "experimental-spirv-reflection", "shader-compiler", "tiles"] }
shred-derive = "0.6"
shred = "0.8"
lazy_static = "1.3"
derivative = "1.0"
failure = "0.1"

imgui = { version = "0.1.0-rc.2" }
imgui-winit-support = { version = "0.1.0-rc.2" }

[[example]]
name = "demo_window"
path = "examples/demo_window.rs"
