[package]
name = "amethyst-imgui"
version = "0.1.0"
description = "imgui library for amethyst"
license = "CC0-1.0"
authors = ["Awpteamoose <cargo@awpteamoose.my.to>"]
repository = "https://github.com/Awpteamoose/amethyst-imgui"
readme = "README.md"
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan", "nightly"] }
shred-derive = "0.6"
shred = "0.8"
lazy_static = "1.3"
derivative = "1.0"
failure = "0.1"
rendy = { git = "https://github.com/amethyst/rendy.git", default-features = false, features = [ "shader", "shader-compiler", "spirv-reflection",  ] }
imgui = { path = "./imgui-rs" }

[[example]]
name = "demo_window"
path = "examples/demo_window.rs"
